## Handling Imbalanced Dataset

1. Up Sampling
2. Down Sampling

In [1]:
import numpy as np
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [2]:
n_class_0

900

In [3]:
n_class_1

100

In [4]:
# creating a data frame with imbalanced data

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [5]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [7]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [8]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [15]:
# Upsampling

df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [16]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True, #Sample With replacement
         n_samples=len(df_majority),
         random_state=42
        )

In [17]:
df_minority_upsampled

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1
..         ...        ...     ...
952   1.188902   2.189189       1
965   3.919526   1.980541       1
976   2.810326   3.604614       1
942   3.621531   2.168229       1
974   1.160887   2.489203       1

[900 rows x 3 columns]

In [21]:
df_minority_upsampled.shape

(900, 3)

In [22]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [23]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [24]:
df_upsampled

     feature_1  feature_2  target
0    -1.085631   0.551302       0
1     0.997345   0.419589       0
2     0.282978   1.815652       0
3    -1.506295  -0.252750       0
4    -0.578600  -0.292004       0
..         ...        ...     ...
952   1.188902   2.189189       1
965   3.919526   1.980541       1
976   2.810326   3.604614       1
942   3.621531   2.168229       1
974   1.160887   2.489203       1

[1800 rows x 3 columns]

In [27]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## Down Sample

In [28]:
import numpy as np
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [29]:
# creating a data frame with imbalanced data

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [30]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [31]:
# Upsampling

df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [32]:
from sklearn.utils import resample
df_majority_downsample=resample(df_majority,replace=True, #Sample With replacement
         n_samples=len(df_minority),
         random_state=42
        )

In [36]:
df_majority_downsample

     feature_1  feature_2  target
102   0.712265   0.718151       0
435   1.199988   0.574621       0
860   0.304515  -0.759475       0
270  -1.213385   0.675504       0
106   0.179549  -0.202659       0
..         ...        ...     ...
201  -0.598105   1.575650       0
269   0.420180   0.570631       0
862  -0.392309   0.446491       0
815  -0.148405  -0.457929       0
270  -1.213385   0.675504       0

[100 rows x 3 columns]

In [37]:
df_downsampled=pd.concat([df_minority,df_majority_downsample])

In [38]:
df_downsampled.shape

(200, 3)

In [40]:
df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64